name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]


jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.0

      - name: Lint 
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          args: --timeout=5m

      - name: Test 
        run: |
          go mod tidy
          go test -v 
